### ISSUE TITLE
Feature request: 20 minute inteval

### ISSUE THREAD

**Issue by wolfv6** [yuntan/chime#1]
Please add a 20-minutes to the interval preferences.
This is a really nice app.  My doctor prescribed a 20-second exercise to be performed every 20 minutes.

**Comment by yuntan** [comment]
Thank you for your feedback! Currently I have no time to update my project, but I'll take time in several weeks.

**Comment by yuntan** [comment]
I've uploaded new version 0.2.4 with the feature.
