### ISSUE TITLE
Language problem

### ISSUE THREAD

**Issue by kaukah** [yuntan/chime#6]
Since 0.2 version, the language always revert become English.
I've set the language to Indonesian but it keep revert to english language although I've been made many setting changes.

Now, I installed v0.1 manually
because it was work perfectly

**Comment by yuntan** [comment]
Sorry, I can't confirm your problem. And I can't simulate your problem by reading my code. Could you record screen movie on options page and paste it as GIF here? Thanks.

**Comment by yuntan** [comment]
Inactive.
